### ISSUE TITLE
ColorPicker: full RTL support?

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#10900]
Right now the color sliders and rectangle don't make any RTL adjustments. While this is not ideal, it's also not too bad since the direction of color gradients is less meaningful from a user perspective than many other directional UI elements. (In the past the sliders and rectangle made *incomplete* RTL adjustments--a pretty broken experience which I removed in PR #10882.) 

The adjustments which would need to be implemented and maintained are:
- Gradients handled by merge-styles (automatic)
- Gradients not handled by merge-styles due to frequent updates
- Mapping slider and rectangle mouse movements to color values
- Mapping slider and rectangle keystrokes to color values
- Thumb positioning in rectangle and slider (not handled by merge-styles due to frequent updates)

If/when this is done, it should include thorough tests to prevent regressions.

**Comment by soryy708** [comment]
In RTL mode the only bug I can see that breaks usability is the direction of the hue gradient.
I workaround it using CSS like so:

```css
.ms-ColorPicker .ms-ColorPicker-slider {
    background: rgba(0, 0, 0, 0) linear-gradient(to left,red 0px, rgb(255, 0, 153) 10%, rgb(205, 0, 255) 20%, rgb(50, 0, 255) 30%, rgb(0, 102, 255) 40%, rgb(0, 255, 253) 50%, rgb(0, 255, 102) 60%, rgb(53, 255, 0) 70%, rgb(205, 255, 0) 80%, rgb(255, 153, 0) 90%, red 100%) repeat scroll 0% 0%;
}
```
