### ISSUE TITLE
Pivot component - Add Item Styles, want "float: right"

### ISSUE THREAD

**Issue by mikezimm** [microsoft/fluentui#14426]
#### Describe the feature that you would like added

I love the pivot component but would like to have an easy way to push the last pivot to the far right.
Then it could be used as like a "Help" tab or something.
Using the F12, I found that if I set the "button" div style to "float: right" it works perfectly and so simple.  (Screenshot #2) 
Or am I missing something in the docs that says how to do this?

#### What component or utility would this be added to
Pivot

#### Additional context/screenshots

![image](https://user-images.githubusercontent.com/49648086/89724956-b66cc880-d9d7-11ea-93c0-3e9e63271650.png)

![image](https://user-images.githubusercontent.com/49648086/89724977-f9c73700-d9d7-11ea-9d4d-6872626369a4.png)

**Comment by mikezimm** [comment]
I tried these options to no success.  Or is there a way to use the HeaderButtonProps and some css looking for a data tag or something?

headerButtonProps
IButtonProps | { [key: string]: string | number | boolean; }
Props for the header command button. This provides a way to pass in native props, such as data-* and aria-*, for each pivot header/link element.

Here are some things I tried so far.
![image](https://user-images.githubusercontent.com/49648086/89725105-b8d02200-d9d9-11ea-8d7b-5469df5c70c1.png)

**Comment by mikezimm** [comment]
After some experimentation, I did get it to work and solved my own problem.

![image](https://user-images.githubusercontent.com/49648086/89745282-d73d2880-da80-11ea-841f-ec9be0e52854.png)


Sample of code that works:
https://github.com/mikezimm/generic-solution/pull/3/commits/2c7718546f0d93680df9d1b0977ee9499fde849a

.module.scss file:
``` scss
.genericWebpart {
    //  This moves the "Help" Pivot to the far right
    .topPivots *[data-content="Help"]  {
      background-color:  red#c2c2c2 ;
      color: #212121;
      transition: all 0.3s ease;
      float:  right !important;
    }
    //... stuff deleted
}
```
Wrap entire pivot in a className = topPivots
```jsx
   <div className={ styles.topPivots }>
       { MyPivot }
   </div>
```
Pivot component takes my header text and also adds that to data-content which is what the scss is targetting
```jsx
        <PivotItem headerText="Help">
            { infoPage }
        </PivotItem>
```
