### ISSUE TITLE
:not() pseudo-class not detecting class names using makeStyles

### ISSUE THREAD

**Issue by omri08** [microsoft/fluentui#18667]
### Environment Information

- **Package version(s)**:  8.20.2
- **Browser and OS versions**: Windows Chrome,

### Please provide a reproduction of the bug in a codepen:
expected result with sass only:
https://codesandbox.io/s/bold-dew-qyq3m?file=/src/styles.scss
unexpected result with fluent UI using makeStyles
https://codesandbox.io/s/basic-demo-forked-xg5vt?file=/src/index.js
![image](https://user-images.githubusercontent.com/54754198/122956762-f5a2ce80-d389-11eb-89f8-cc6736769751.png)
In the picture, the parent has a class name called `hi,` which means he should not have the `background-color: blue` style. 
#### Actual behavior:
The `:not()` pseudo-class not detecting the class name that causing applying the wrong style

#### Expected behavior:
The `:not()` pseudo-class needs to detect the class name and not apply the style.

**Comment by gouttierre** [comment]
@omri08 - Thanks for filing this issue with us.

@smhigley - Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @layershifter

**Comment by layershifter** [comment]
> * **Package version(s)**:  8.20.2

@gouttierre this issue is related to v8, not to v9. `makeStyles()` has completely different implementation there. @microsoft/cxe-red owns it 😉

**Comment by smhigley** [comment]
@dzearing do you still own ThemeProvider, and if so, do you have a sense of where the issue is?

@omri08 this looks like a bug specifically around the combination of `:not()` and `::before`. If you define them separately rather than nesting them, it works:

```css
const useStyle = makeStyles(() => ({
  beginof: {
    "&:before": {
      content: '"<<>>"'
    },
    "&:not(.hi)": {
      backgroundColor: 'red',
    },
    "&:not(.hi)::before": {
      backgroundColor: "blue"
    }
  }
}));
```

Does that work for you as a workaround for now?
