### ISSUE TITLE
makeStyles: Direction based style awareness and flipping css variable values

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#20574]
# Problems

## Flipping complex css values in css variables

When using css variables as scalar values, it's pretty easy to handle flipping, since you're just flipping the actual property.

```css
body {
  --spacing-xs: 5px;
}

.style {
  marginLeft: var(--spacing-xs);
  padding: var(--spacing-xs) var(--spacing-xs);
}
```

Flipping more complex css values is not possible using css-in-js combined with css variables

```css
body {
  --shadow: 0 0 2px red, 0 1px 2px red;
  --spacing-lg: 30px;
  --spacing-m: 20px;
  --deg: 20deg;
}

/* There is no way to sanely flip these values */
.style {
  transform: translate(var(--spacing-lg), var(--spacing-m)) rotate(var(--deg));
  box-shadow: var(--shadow) 
}
```
## Direction aware styles

Additionally there will be a need for styles that are RTL aware, it might not happen often but there are enough cases at least in Teams to give this some thought. Below is an example taken from the real application.

```ts
{
  transform: rtl
    ? "rotate(-90deg) /* @noflip */"
    : "rotate(90deg) /* @noflip */", 
}
```

Since we use the same [rtl-css-js](https://github.com/kentcdodds/rtl-css-js) package as in v0, we can quite easily use the same `/* @noflip */` syntax to ignore flipping. However currently in makeStyles there is no way to apply styles that either:

* apply only for ltr
* apply only for rtl
* apply differently for rtl and ltr

# Solutions to explore

Once a feasible approach(es) has been discovered the proposal should be written up as an RFC and discused in the team.

## Compute RTL theme values

Since we control our theme, we can identify complex values and pre compute RTL values. This is a pre-requisite to the below proposed solutions if we want any kind of RTL handling at all in our theme tokens.

`theme.shadow16 -> theme.shadow16Rtl`

## Array css values in makeStyles

```ts
makeStyles(
  root: theme => ({
    boxShadow: [theme.shadow16, theme.shadow16Rtl],
  })
)
```

## RTL selector for makeStyles
Add a makeStyles specific selector similar the current `:global([selector])` that will override any styles that overlap with the parent set of styles in RTL mode.

```ts
makeStyles(
  root: theme => ({
    boxShadow: theme.shadow16
    ':rtl': {
      boxShadow: theme.shadow16Rtl
    }
  })
)
```
